version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: soulence-postgres
    environment:
      POSTGRES_DB: soulence
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    networks:
      - soulence-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: soulence-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - soulence-network

  # InfluxDB for Time-Series Data
  influxdb:
    image: influxdb:2.7-alpine
    container_name: soulence-influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password123
      DOCKER_INFLUXDB_INIT_ORG: soulence
      DOCKER_INFLUXDB_INIT_BUCKET: mood-metrics
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: soulence-token-123
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - soulence-network

  # Apache Kafka for Event Streaming
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: soulence-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - soulence-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: soulence-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - soulence-network

  # MinIO for S3-compatible Object Storage
  minio:
    image: minio/minio:latest
    container_name: soulence-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    networks:
      - soulence-network

  # Elasticsearch for Logging
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: soulence-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - soulence-network

  # Kibana for Log Visualization
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.0
    container_name: soulence-kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - soulence-network

  # Prometheus for Metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: soulence-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - soulence-network

  # Grafana for Visualization
  grafana:
    image: grafana/grafana:latest
    container_name: soulence-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - soulence-network

  # Auth Service
  auth-service:
    build:
      context: ./backend/services/auth
      dockerfile: Dockerfile
    container_name: soulence-auth-service
    depends_on:
      - postgres
      - redis
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      AUTH_SERVICE_PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: soulence
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev-secret-change-in-production
    networks:
      - soulence-network

volumes:
  postgres_data:
  redis_data:
  influxdb_data:
  minio_data:
  elasticsearch_data:
  prometheus_data:
  grafana_data:

networks:
  soulence-network:
    driver: bridge