global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Wellness Service (when implemented)
  - job_name: 'wellness-service'
    static_configs:
      - targets: ['wellness-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Academic Service (when implemented)
  - job_name: 'academic-service'
    static_configs:
      - targets: ['academic-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Learning Service (when implemented)
  - job_name: 'learning-service'
    static_configs:
      - targets: ['learning-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Care Service (when implemented)
  - job_name: 'care-service'
    static_configs:
      - targets: ['care-service:3005']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node Exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093